import {newGame,moves,square,PIECES,NAMES,TYPES,inCheck,validateSave,positionKey,migrateRoster,ROSTER_SIZE} from './engine.mjs';
import {Match} from './match.mjs';
import {surge} from './arena.mjs';
import {drawArena} from './render.mjs';
import {loadArtwork} from './art.mjs';
// Champion icons are crops of each champion's idle sprite, trimmed to the figure (Black's face left).
const ICON_BOX={rock:{x:49,y:73,w:223,h:206},scissors:{x:51,y:345,w:221,h:224},paper:{x:33,y:635,w:179,h:200}};
function champIcon(t,s='w',size=34){const f=ICON_BOX[t],k=size/f.h;return `<span class="champ-icon${s==='b'?' flip':''}" aria-hidden="true" style="width:${Math.round(f.w*k)}px;height:${size}px;background-size:${Math.round(1774*k)}px ${Math.round(887*k)}px;background-position:${-Math.round(f.x*k)}px ${-Math.round(f.y*k)}px"></span>`;}
import {benchHtml} from './benches.mjs';
import {pieceSvg} from './pieces.mjs';
import {autoInput} from './bots.mjs';
import {SoundBank} from './sound.mjs';
const $=id=>document.getElementById(id),TEAM={w:'White',b:'Black'},ROLE={rock:'The juggernaut',scissors:'The assassin',paper:'The mage'},GLYPH={p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'};
const STORE='cherpss-v1',keys=new Set(),pressed=new Set();let selected=null,promotionMoves=[],saveTimer=0,aftermathUntil=0,resultShown=false,frameNow=0,toastTimer,lastFrame=0,hudTimer=0,controllerSeen=false,previousPads={},storageAvailable=true;
const detectedPhone=!!window.matchMedia?.('(pointer: coarse)').matches&&!!window.matchMedia?.('(max-width: 900px)').matches;
let controlPreference=null,automatic=detectedPhone,handoff=false,moveHints=true;
let match=new Match(),saved=null;
// Reloading must not reroll a duel: the running fight is saved and resumes after a short countdown.
// Projectiles point at their caster; store that as a side so the snapshot is plain JSON.
function duelSnapshot(){const w=match.world;return{selection:match.selection,world:{...w,events:[],projectiles:w.projectiles.map(p=>({...p,source:p.source.s}))}};}
function resumeDuel(duel){
 const w=duel?.world;if(match.phase!=='pick'||!w||!Array.isArray(w.fighters)||w.fighters.length!==2||w.done)return;
 const sel=duel.selection;if(!TYPES.includes(sel?.w)||!TYPES.includes(sel?.b)||w.fighters.some(f=>f.t!==sel[f.s]))return;
 const by={w:w.fighters.find(f=>f.s==='w'),b:w.fighters.find(f=>f.s==='b')};if(!by.w||!by.b)return;
 w.projectiles=(w.projectiles??[]).map(p=>({...p,source:by[p.source]})).filter(p=>p.source);
 w.events=[];w.countdown=Math.max(w.countdown??0,1.5);w.lastCountdown=null;
 match.selection={...sel};match.world=w;match.phase='fight';
}

try{saved=JSON.parse(localStorage.getItem(STORE));if(saved&&validateSave(saved.game)){controlPreference=['auto','manual'].includes(saved.controlPreference)?saved.controlPreference:null;automatic=controlPreference?controlPreference==='auto':detectedPhone;moveHints=saved.moveHints!==false;match=new Match(migrateRoster(saved.game),saved.duration===60?60:null);if(saved.resolved&&match.phase==='continuation')match.keepWin();if(saved.pending&&match.phase==='board'&&match.play(saved.pending))resumeDuel(saved.duel);}}catch{storageAvailable=false;}
const sfx=new SoundBank(saved?.soundEnabled!==false);
window.addEventListener('pointerdown',()=>sfx.unlock());window.addEventListener('keydown',()=>sfx.unlock());
const ctx=$('arena').getContext('2d');
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function save(){try{localStorage.setItem(STORE,JSON.stringify({game:match.game,duration:match.duration,controlPreference,moveHints,soundEnabled:sfx.enabled,resolved:match.phase==='gameover',pending:!match.practice&&['pick','fight'].includes(match.phase)?match.pending:null,duel:!match.practice&&match.phase==='fight'?duelSnapshot():null}));}catch{storageAvailable=false;}$('saveNote').textContent=storageAvailable?'Local play · no game accounts · progress saved on this device':'Local play · saving unavailable in this browser session';}
// Each roster card shows how many champions of that type are left, one pip each.
function renderRoster(s){const reveal=['fight','result'].includes(match.phase);$('roster-'+s).innerHTML=TYPES.map(t=>{const left=match.practice?ROSTER_SIZE:match.game.roster[s][t];return `<div class="roster-card ${left<=0?'exhausted':''} ${reveal&&match.selection[s]===t?'active':''}"><span class="monster-icon">${champIcon(t,s)}</span><div><strong>${NAMES[t]}</strong><small>${ROLE[t]}${left<=0?' · none left':''}</small></div><div class="vitality-row" aria-label="${left} of ${ROSTER_SIZE} left"><span class="pips">${Array.from({length:ROSTER_SIZE},(_,i)=>`<i class="${i<left?'on':''}"></i>`).join('')}</span><span>${left} left</span></div></div>`;}).join('');}
function renderBoard(){
 const g=match.game,legal=selected===null?[]:moves(g,selected),targets=new Set(legal.map(m=>m.to));$('board').replaceChildren();
 for(let i=0;i<64;i++){const p=g.board[i],b=document.createElement('button');b.type='button';b.className='square'+(((i>>3)+i%8)%2?' dark':'')+(selected===i?' selected':'')+(moveHints&&targets.has(i)?' legal':'')+(moveHints&&targets.has(i)&&p?' capture':'')+([g.last?.from,g.last?.to].includes(i)?' last':'')+(g.mode==='classic'&&p?.t==='k'&&inCheck(g,p.s)?' check':'');b.setAttribute('aria-label',`${square(i)}${p?' · '+TEAM[p.s]+' '+PIECES[p.t]:', empty'}${targets.has(i)?' · available move':''}`);b.setAttribute('aria-pressed',String(selected===i));b.dataset.square=i;b.addEventListener('click',()=>boardClick(i));b.addEventListener('keydown',e=>{const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8}[e.code];if(d!==undefined){e.preventDefault();const next=Math.max(0,Math.min(63,i+d));$('board').children[next]?.focus();}});if(p)b.innerHTML=pieceSvg(p.t,p.s);b.disabled=match.phase!=='board';$('board').append(b);}
 const check=g.mode==='classic'&&inCheck(g,g.turn);$('boardCaption').textContent=g.mode==='classic'?(check?`${TEAM[g.turn]} is in check.`:'Ordinary chess · captures are final · kings must stay safe.'):moveHints?'Click a piece, then a highlighted square. Captures become duels.':'Click a piece, then its destination. Captures become duels.';
}
function boardClick(i){if(match.phase!=='board')return;const p=match.game.board[i];if(selected!==null){const options=moves(match.game,selected).filter(m=>m.to===i);if(options.length){if(options[0].promote){promotionMoves=options;$('promotionOptions').replaceChildren();for(const m of options){const b=document.createElement('button');b.innerHTML=`${pieceSvg(m.promote,match.game.turn)}<small>${PIECES[m.promote]}</small>`;b.addEventListener('click',()=>{$('promotionDialog').close();play(m);});$('promotionOptions').append(b);}$('promotionDialog').showModal();return;}play(options[0]);return;}}
 selected=p?.s===match.game.turn?(selected===i?null:i):null;renderBoard();
}
function play(m){if(match.play(m)){selected=null;handoff=false;keys.clear();pressed.clear();sfx.play('move');save();render();}}
// The duel result sits in the middle of the arena so both benches stay visible around it.
function resultCard(html){$('resultCard').hidden=false;$('resultCard').innerHTML=html;resultShown=true;}
function overlay(html){$('stageOverlay').hidden=false;$('stageOverlay').innerHTML='<div class="stage-content">'+html+'</div>';}
function render(){
 const g=match.game,phase=match.phase;$('modeLabel').textContent=match.practice?'JUST A FRIENDLY SCRAP':g.mode==='classic'?'ORDINARY CHESS':'CHESS MEETS THE ARENA';$('headline').textContent=phase==='fight'?'The board set the stage. Now fight.':phase==='pick'?'Choose your champion. Keep it secret.':phase==='result'?'The dust settles.':phase==='gameover'?'The match is decided.':g.mode==='classic'?'Let the position speak.':'Plan your move. Pick your fight.';
 document.body.classList.toggle('auto-battles',automatic);document.body.classList.toggle('arena-open',['pick','fight','result'].includes(phase));$('autoBtn').textContent=automatic?'Battles: automatic':'Battles: manual';$('autoBtn').setAttribute('aria-pressed',String(automatic));$('autoBtn').disabled=phase==='fight';$('battleNote').textContent=automatic?'Pass-and-play champion picks · automatic battles':match.duration===60?'Shared keyboard or controllers · one-minute duels':'Shared keyboard or controllers · unlimited duels';
 $('hintsBtn').textContent=moveHints?'Move hints: on':'Move hints: off';$('hintsBtn').setAttribute('aria-pressed',String(moveHints));$('soundBtn').textContent=sfx.enabled?'Sound on':'Sound off';$('soundBtn').setAttribute('aria-pressed',String(sfx.enabled));
 $('boardMode').textContent=g.mode==='classic'?'CLASSIC CHESS':'DUEL CHESS';$('status').textContent=phase==='board'?TEAM[g.turn]+' to move':phase==='pick'?'Secret selection':phase==='fight'?'Arena duel':phase==='result'?'Duel finished':'Match finished';
 for(const s of ['w','b']){$('turn-'+s).hidden=phase!=='board'||g.turn!==s;renderRoster(s);$('support-'+s).innerHTML=['pick','fight','result'].includes(phase)?benchHtml(match.support?.[s],s,match.support?.centre):'';}
 const arena=phase==='fight'||phase==='result'&&!!match.world;$('boardArea').hidden=arena;$('arenaArea').hidden=!arena;$('stageOverlay').hidden=true;$('resultCard').hidden=true;resultShown=false;$('newBtn').disabled=phase==='fight';$('rulesBtn').disabled=phase==='fight';
 renderBoard();$('moveCount').textContent=g.ply+' moves';$('historyList').replaceChildren();for(const line of [...g.history].reverse().slice(0,30)){const li=document.createElement('li');li.textContent=line;$('historyList').append(li);}
 if(phase==='pick'){
  const centre=match.support.centre;overlay(`<span class="eyebrow">${match.practice?'PRACTICE DUEL':`CHALLENGE AT ${square(centre).toUpperCase()}`}</span><h2>Two choices. One showdown.</h2><p>Choose on your side of the keyboard.<br>Both champions appear together when you're ready.</p><div class="pick-columns">${['w','b'].map(s=>`<div class="pick-box"><strong style="color:${s==='w'?'var(--ivory)':'var(--ember)'}">${TEAM[s]}</strong><div class="choice-line">${TYPES.map((t,i)=>`<kbd>${s==='w'?['F','G','H'][i]:['J','K','L'][i]}</kbd> ${NAMES[t]}${!match.practice&&g.roster[s][t]<=0?' · unavailable':''}`).join('<br>')}</div><p class="ready-state">${match.selection[s]?'✓ LOCKED IN':'WAITING FOR YOUR CHOICE'}</p></div>`).join('')}</div><div class="support-preview">Controller choices: A Rock · X Scissors · B Paper<br>${match.practice?'A fresh roster. Your match will stay as it is.':'Your local formation will support your champion.'}</div>${match.practice?'<div class="stage-actions"><button id="cancelPractice" class="secondary">Back to board</button></div>':''}`);
  if(automatic)renderTouchPick();
  if(match.practice&&$('cancelPractice'))$('cancelPractice').onclick=()=>{match.practice=false;match.phase=match.returnPhase;handoff=false;render();};
 }else if(phase==='result'&&frameNow<aftermathUntil){
  // A short aftermath first: the winner celebrates, the loser collapses, the benches react.
 }else if(phase==='result'){
  const winner=match.result.winner,loser=winner?winner==='w'?'b':'w':null;(match.world?resultCard:overlay)(`<span class="eyebrow">${match.result.practice?'PRACTICE COMPLETE':'THE DUST SETTLES'}</span><h2>${winner?TEAM[winner]+' wins the duel':'A double defeat'}</h2><span class="result-pill">${match.result.reason}</span><p>${match.practice?'Try another champion, or return to your board.':winner?`${winner===match.result.attacker?'The capture succeeds.':'The defender holds. The attacker is removed.'}<br>${TEAM[loser]} loses a ${NAMES[match.selection[loser]]} champion (${match.game.roster[loser][match.selection[loser]]} left).`:'Both board pieces are removed. Both champions are eliminated.'}</p><div class="stage-actions"><button id="continueBtn" class="primary">${match.practice?'Back to board':'Return to board →'}</button>${match.practice?'<button id="againBtn" class="secondary">Another duel</button>':''}</div>`);
  $('continueBtn').onclick=()=>{match.continueAfterDuel();keys.clear();save();render();};if(match.practice)$('againBtn').onclick=()=>{match.phase=match.returnPhase;match.practice=false;match.practiceStart();keys.clear();render();};
 }else if(phase==='continuation'){
  const winner=match.ending.winner,loser=match.ending.loser;
  if(match.offerStage==='loser')overlay(`<span class="eyebrow">${match.ending.reason.toUpperCase()}</span><h2>${winner?TEAM[winner]+' wins the brawl':'Both rosters are exhausted'}</h2><p>${loser?TEAM[loser]+', accept the defeat or ask for one last challenge on the chessboard.':'You can agree to settle this with ordinary chess.'}</p>${match.offerIssue?`<p>${match.offerIssue}</p>`:''}<div class="stage-actions"><button id="keepBtn" class="secondary">${winner?'Accept defeat':'Finish match'}</button><button id="requestBtn" class="primary" ${match.offerIssue?'disabled':''}>Request ordinary chess</button></div>`);
  else overlay(`<span class="eyebrow">A FINAL CHALLENGE</span><h2>${winner?TEAM[winner]+', your choice.':'Continue on the board?'}</h2><p>The same position. Ordinary chess rules.<br>Accept the challenge, or keep the brawl result.</p><div class="stage-actions"><button id="keepBtn" class="secondary">${winner?'Keep my win':'Keep the draw'}</button><button id="acceptBtn" class="primary">Accept · play chess</button></div>`);
  $('keepBtn').onclick=()=>{match.keepWin();save();render();};if($('requestBtn'))$('requestBtn').onclick=()=>{match.requestChess();render();};if($('acceptBtn'))$('acceptBtn').onclick=()=>{match.acceptChess();selected=null;save();render();};
 }else if(phase==='gameover'){
  overlay(`<span class="eyebrow">MATCH COMPLETE</span><h2>${match.ending.winner?TEAM[match.ending.winner]+' wins':'A worthy draw'}</h2><p>${match.ending.reason}</p><div class="stage-actions"><button id="rematchBtn" class="primary">Play again</button><button id="viewBoardBtn" class="secondary">View final board</button></div>`);$('rematchBtn').onclick=()=>$('newDialog').showModal();$('viewBoardBtn').onclick=()=>{$('stageOverlay').hidden=true;$('boardCaption').textContent=match.ending.reason+' · use New match to play again.';};
 }
 if(phase==='fight'){hud();drawArena(ctx,match.world,match.support);}
}
function hud(){if(!match.world)return;for(const f of match.world.fighters){$('hud-'+f.s).innerHTML=`<div class="hud-name">${TEAM[f.s]} · ${NAMES[f.t]}</div><div class="hp-track"><i style="width:${Math.max(0,100*f.hp/f.maxHp)}%"></i></div><div class="hud-sub">${Math.ceil(f.hp)} HP · ${Math.ceil(f.stamina)} guard · ${f.specialCd>0?'special '+f.specialCd.toFixed(1)+'s':'SPECIAL READY'}${f.shield>0?' · shield '+Math.ceil(f.shield):''}</div>`;}$('clock').textContent=match.world.time===null?'∞':Math.ceil(match.world.time);const att=match.world.fighters.find(f=>f.s===match.world.attacker),boost=att?surge(match.world,att):1;$('lightLabel').textContent=boost>1?`${TEAM[match.world.attacker].toUpperCase()} SURGE ×${boost.toFixed(1)}`:(match.world.night?'BLACK REALM':'WHITE REALM')+(automatic?' · AUTO':'');}
function choose(s,t){const before=match.phase;if(match.choose(s,t)){handoff=automatic&&match.phase==='pick';keys.clear();pressed.clear();sfx.play('select');render();if(before!==match.phase)lastFrame=0;}else if(match.game.roster[s][t]<=0)toast(NAMES[t]+' is exhausted. Choose another champion.');}
function renderTouchPick(){const s=match.selection.w?'b':'w',cancel=match.practice?'<div class="stage-actions"><button id="cancelPractice" class="secondary">Back to board</button></div>':'';
 if(handoff){overlay(`<span class="eyebrow">FIRST CHOICE LOCKED IN</span><h2>Pass to ${TEAM[s]}</h2><p>The other player should look away.<br>The first champion stays hidden.</p><div class="stage-actions"><button id="handoffBtn" class="primary">${TEAM[s]} is ready</button></div>${cancel}`);$('handoffBtn').onclick=()=>{handoff=false;render();};return;}
 overlay(`<span class="eyebrow">${match.practice?'PRACTICE · ':''}PRIVATE CHAMPION PICK</span><h2>${TEAM[s]}, choose your champion</h2><p>Other player, look away.<br>Both champions reveal together, then fight automatically.</p><div class="touch-choices">${TYPES.map(t=>`<button id="touch-${t}" ${!match.practice&&match.game.roster[s][t]<=0?'disabled':''}><span>${champIcon(t,s,64)}</span><strong>${NAMES[t]}</strong><small>${ROLE[t]}</small></button>`).join('')}</div>${cancel}`);for(const t of TYPES)$('touch-'+t).onclick=()=>choose(s,t);
}
const mapping={w:{up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',attack:'KeyF',guard:'KeyG',special:'KeyH'},b:{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',attack:'KeyJ',guard:'KeyK',special:'KeyL'}};
const choiceKeys={KeyF:['w','rock'],KeyG:['w','scissors'],KeyH:['w','paper'],KeyJ:['b','rock'],KeyK:['b','scissors'],KeyL:['b','paper']};
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(!['pick','fight'].includes(match.phase))return;const recognised=Object.values(mapping).some(m=>Object.values(m).includes(e.code));if(recognised)e.preventDefault();if(match.phase==='pick'&&!e.repeat&&choiceKeys[e.code]){choose(...choiceKeys[e.code]);return;}if(match.phase==='fight'){if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pressed.clear();});
// Attacks and specials fire on the press itself: holding the key does nothing more, so every blow is a tap.
function input(){const out={};for(const s of ['w','b']){const m=mapping[s];out[s]={x:Number(keys.has(m.right))-Number(keys.has(m.left)),y:Number(keys.has(m.down))-Number(keys.has(m.up)),attack:pressed.has(m.attack),guard:keys.has(m.guard),special:pressed.has(m.special)};}return out;}
function pads(controls){const list=Array.from(navigator.getGamepads?.()??[]).filter(Boolean).slice(0,2);if(list.length&&!controllerSeen){controllerSeen=true;toast('Controller connected. First pad is White; second is Black.');}for(let i=0;i<list.length;i++){const p=list[i],s=i===0?'w':'b',prev=previousPads[p.index]??[];const down=n=>!!p.buttons[n]?.pressed;const edge=n=>down(n)&&!prev[n];if(match.phase==='pick'){if(edge(0))choose(s,'rock');else if(edge(2))choose(s,'scissors');else if(edge(1))choose(s,'paper');}else if(match.phase==='fight'){if(Math.abs(p.axes[0]??0)>.2)controls[s].x=p.axes[0];if(Math.abs(p.axes[1]??0)>.2)controls[s].y=p.axes[1];if(down(14))controls[s].x=-1;if(down(15))controls[s].x=1;if(down(12))controls[s].y=-1;if(down(13))controls[s].y=1;controls[s].attack||=edge(0);controls[s].guard||=down(2);controls[s].special||=edge(1);}previousPads[p.index]=p.buttons.map(b=>b.pressed);}}
function frame(now){frameNow=now;const dt=lastFrame?Math.min(.04,(now-lastFrame)/1000):0;lastFrame=now;const controls=input();if(!automatic)pads(controls);pressed.clear();if(match.phase==='fight'){match.tick(dt,automatic?autoInput(match.world):controls);for(const event of match.world.events)sfx.play(event);match.world.events=[];if(match.phase==='result'){aftermathUntil=now+2400;save();render();}else{drawArena(ctx,match.world,match.support);hudTimer+=dt;if(hudTimer>.08){hud();hudTimer=0;}saveTimer+=dt;if(saveTimer>.5){save();saveTimer=0;}}}
 else if(match.phase==='result'&&match.world){drawArena(ctx,match.world,match.support);if(!resultShown&&now>=aftermathUntil)render();}
 requestAnimationFrame(frame);}
$('hintsBtn').onclick=()=>{moveHints=!moveHints;save();render();};
$('autoBtn').onclick=()=>{if(match.phase==='fight')return;automatic=!automatic;controlPreference=automatic?'auto':'manual';handoff=false;keys.clear();pressed.clear();save();render();};
$('rulesBtn').onclick=()=>$('rulesDialog').showModal();$('newBtn').onclick=()=>$('newDialog').showModal();$('soundBtn').onclick=()=>{sfx.setEnabled(!sfx.enabled);sfx.play('select');save();render();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('startBtn').onclick=()=>{match=new Match(newGame($('modeSelect').value),$('durationSelect').value==='60'?60:null);selected=null;handoff=false;keys.clear();pressed.clear();$('newDialog').close();save();render();};
loadArtwork().then(ok=>{if(!ok)toast('Some artwork could not load. Please refresh to try again.');render();});
render();save();requestAnimationFrame(frame);
if(saved&&validateSave(saved.game))toast('Your match is back.');
