import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,moves,allMoves,applyMove,inCheck,classicStatus,collectSupport,bonuses,continuationIssue,validateSave,recordWounds,positionKey} from '../../cherpss/engine.mjs';
import {makeArena,stepArena,STATS,RULES} from '../../cherpss/arena.mjs';
// Let a Rock's wind-up (or a bolt's flight) finish, holding the given input.
const settle=(w,input={},n=30)=>{for(let i=0;i<n;i++)stepArena(w,.016,input);};
import {Match} from '../../cherpss/match.mjs';
import {autoInput} from '../../cherpss/bots.mjs';
const idx=s=>(8-Number(s[1]))*8+'abcdefgh'.indexOf(s[0]);
function position(fen,turn='w',mode='classic'){const g=newGame(mode);g.board=[];for(const row of fen.split('/'))for(const c of row){if(/[1-8]/.test(c))g.board.push(...Array(Number(c)).fill(null));else g.board.push({s:c===c.toUpperCase()?'w':'b',t:c.toLowerCase()});}g.turn=turn;g.rights={wK:false,wQ:false,bK:false,bQ:false};g.repetitions={[positionKey(g)]:1};return g;}
function move(g,a,b,promote){const m=moves(g,idx(a)).find(m=>m.to===idx(b)&&(!promote||m.promote===promote));assert.ok(m,`${a}-${b} should be available`);return applyMove(g,m);}
function perft(g,d){return d===0?1:allMoves(g).reduce((n,m)=>n+perft(applyMove(g,m),d-1),0);}
test('standard chess move tree matches known opening counts',()=>{const g=newGame('classic');assert.equal(perft(g,1),20);assert.equal(perft(g,2),400);assert.equal(perft(g,3),8902);});
test('Fool’s mate ends classic chess with checkmate',()=>{let g=newGame('classic');for(const[a,b]of[['f2','f3'],['e7','e5'],['g2','g4'],['d8','h4']])g=move(g,a,b);assert.deepEqual(classicStatus(g),{over:true,winner:'b',reason:'Checkmate'});});
test('classic king cannot move into check or capture the other king',()=>{const g=position('8/8/8/8/8/4k3/8/4K3');assert.ok(!moves(g,idx('e1')).some(m=>m.to===idx('e2')));const h=position('8/8/8/8/8/8/4k3/4K3');assert.ok(!moves(h,idx('e1')).some(m=>m.to===idx('e2')));});
test('castling shifts the rook and king, but cannot cross attack in classic chess',()=>{let g=position('4k3/8/8/8/8/8/8/R3K2R');g.rights.wK=true;g.rights.wQ=true;assert.ok(moves(g,60).some(m=>m.castle&&m.to===62));g=move(g,'e1','g1');assert.equal(g.board[61].t,'r');assert.equal(g.board[62].t,'k');assert.equal(g.rights.wK,false);const h=position('4kr2/8/8/8/8/8/8/4K2R');h.rights.wK=true;assert.ok(!moves(h,60).some(m=>m.castle));});
test('moving a rook revokes the relevant castling right permanently',()=>{let g=position('4k3/8/8/8/8/8/8/R3K2R');g.rights.wQ=true;g=move(g,'a1','a2');assert.equal(g.rights.wQ,false);});
test('en passant removes the passed pawn and expires after another move',()=>{let g=newGame('classic');for(const[a,b]of[['e2','e4'],['a7','a6'],['e4','e5'],['d7','d5']])g=move(g,a,b);const m=moves(g,idx('e5')).find(m=>m.to===idx('d6'));assert.equal(m.epCapture,idx('d5'));g=applyMove(g,m);assert.equal(g.board[idx('d5')],null);assert.equal(g.board[idx('d6')].t,'p');assert.equal(g.ep,null);});
test('en passant cannot expose the moving side’s king',()=>{const g=position('8/8/8/r4pPK/8/8/8/7k');g.ep=idx('f6');assert.ok(!moves(g,idx('g5')).some(m=>m.to===idx('f6')));});
test('pawn promotion supports queen, rook, bishop and knight',()=>{const g=position('7k/P7/8/8/8/8/8/7K');assert.deepEqual(moves(g,8).filter(m=>m.to===0).map(m=>m.promote),['q','r','b','n']);assert.equal(move(g,'a7','a8','n').board[0].t,'n');});
test('duel chess deliberately permits challenges to a king',()=>{const g=position('4k3/4R3/8/8/8/8/8/4K3','w','duel');assert.ok(moves(g,12).some(m=>m.to===4));});
test('a failed capture removes only the attacker and keeps the defender',()=>{const g=position('4k3/8/8/8/3p4/4P3/8/4K3','w','duel');const m=moves(g,idx('e3')).find(m=>m.to===idx('d4'));const next=applyMove(g,m,false);assert.equal(next.board[idx('e3')],null);assert.deepEqual(next.board[idx('d4')],{s:'b',t:'p'});assert.equal(next.turn,'b');});
test('support counts the jumping attacker once and vacates its origin',()=>{const g=position('4k3/8/8/3p4/2N1B3/8/8/4K3','w','duel');const m=moves(g,idx('c4')).find(m=>m.to===idx('d6')); // not a capture; collectSupport still tests geometry
 assert.ok(m);const support=collectSupport(g,{from:idx('c4'),to:idx('d5')});assert.equal(support.w.filter(p=>p.t==='n').length,1);assert.equal(support.w.filter(p=>p.t==='b').length,1);assert.equal(support.b.length,1);assert.equal(support.centre,idx('d5'));});
test('3×3 support clips correctly at a corner',()=>{const g=position('p6k/1B6/8/8/8/8/8/R6K','w','duel');const support=collectSupport(g,{from:56,to:0});assert.equal(support.pieces.length,3);});
test('support bonuses have explicit caps',()=>{const b=bonuses(['p','n','b','r','q','k'].flatMap(t=>Array.from({length:30},()=>({t}))));assert.equal(b.shield,24);assert.equal(b.speed,.05);assert.equal(b.cooldown,1-.3);assert.equal(b.power,.45);assert.equal(b.attackSpeed,.4);assert.equal(b.damage,1.2);assert.equal(b.cover,0);});
test('secret selections cannot be changed and only both choices start combat',()=>{const m=new Match();m.practiceStart();assert.equal(m.choose('w','rock'),true);assert.equal(m.phase,'pick');assert.equal(m.choose('w','paper'),false);assert.equal(m.choose('b','paper'),true);assert.equal(m.phase,'fight');assert.equal(m.world.fighters[0].t,'rock');});
test('exhausted champions cannot be selected',()=>{const m=new Match(position('4k3/8/8/8/3p4/4P3/8/4K3','w','duel'));m.game.roster.w.rock=0;m.play(moves(m.game,idx('e3')).find(x=>x.to===idx('d4')));assert.equal(m.choose('w','rock'),false);assert.equal(m.choose('w','paper'),true);});
test('duel result updates board and persistent health before returning to board',()=>{const m=new Match(position('4k3/8/8/8/3p4/4P3/8/4K3','w','duel'));m.play(moves(m.game,idx('e3')).find(x=>x.to===idx('d4')));m.choose('w','rock');m.choose('b','scissors');m.finishDuel({winner:'w',reason:'Knockout',damage:{w:20,b:92}});assert.equal(m.phase,'result');assert.equal(m.game.board[idx('d4')].s,'w');assert.equal(m.game.roster.b.scissors,60);assert.equal(m.game.roster.w.rock,96);m.continueAfterDuel();assert.equal(m.phase,'board');});
test('practice does not mutate the board, roster, or journal',()=>{const m=new Match();const before=structuredClone(m.game);m.practiceStart();m.choose('w','paper');m.choose('b','rock');m.finishDuel({winner:'w',reason:'Knockout',damage:{w:40,b:125}});m.continueAfterDuel();assert.deepEqual(m.game,before);assert.equal(m.phase,'board');});
test('defeating a king ends a match after its duel',()=>{const m=new Match(position('4k3/4R3/8/8/8/8/8/4K3','w','duel'));m.play(moves(m.game,12).find(x=>x.to===4));m.choose('w','rock');m.choose('b','paper');m.finishDuel({winner:'w',reason:'Knockout',damage:{w:0,b:100}});m.continueAfterDuel();assert.equal(m.phase,'gameover');assert.equal(m.ending.winner,'w');});
test('roster exhaustion requires both players to agree before classic continuation',()=>{const g=newGame();g.roster.w={rock:0,scissors:0,paper:0};const m=new Match(g);assert.equal(m.phase,'continuation');assert.equal(m.acceptChess(),false);assert.equal(m.requestChess(),true);assert.equal(m.phase,'continuation');assert.equal(m.acceptChess(),true);assert.equal(m.game.mode,'classic');assert.equal(m.phase,'board');});
test('winner can decline continuation and keep the result',()=>{const g=newGame();g.roster.b={rock:0,scissors:0,paper:0};const m=new Match(g);m.requestChess();m.keepWin();assert.equal(m.phase,'gameover');assert.equal(m.ending.winner,'w');});
test('invalid classic positions disable continuation',()=>{const g=position('8/8/8/8/8/8/4k3/4K3','w','duel');assert.ok(continuationIssue(g));});
test('draws include stalemate, insufficient material and fifty moves',()=>{assert.equal(classicStatus(position('7k/5Q2/6K1/8/8/8/8/8','b')).reason,'Stalemate');assert.equal(classicStatus(position('7k/8/8/8/8/8/8/K7')).reason,'Draw · insufficient material');const g=newGame('classic');g.half=100;assert.equal(classicStatus(g).reason,'Draw · fifty-move rule');});
test('repetition is recorded during normal play',()=>{let g=newGame('classic');for(let i=0;i<2;i++)for(const[a,b]of[['g1','f3'],['g8','f6'],['f3','g1'],['f6','g8']])g=move(g,a,b);assert.equal(classicStatus(g).reason,'Draw · threefold repetition');});
test('saved game validation rejects corrupted board and health values',()=>{const g=newGame();assert.equal(validateSave(g),true);g.roster.w.rock=-1;assert.equal(validateSave(g),false);assert.equal(validateSave({board:[]}),false);});
function world(a='rock',b='paper',options={}){return makeArena({w:a,b:b},{w:[],b:[]},newGame().roster,{duration:null,attacker:null,...options});}
test('arena countdown prevents early damage and movement',()=>{const w=world(),before=structuredClone(w.fighters);stepArena(w,.04,{w:{x:1,attack:true},b:{attack:true}});assert.equal(w.fighters[0].x,before[0].x);assert.equal(w.fighters[1].hp,before[1].hp);});
test('melee attacks require range and facing',()=>{const w=world('rock','scissors');w.countdown=0;w.fighters[1].x=210;stepArena(w,.016,{w:{attack:true}});settle(w);assert.ok(w.fighters[1].hp<STATS.scissors.hp);const x=world('rock','scissors');x.countdown=0;x.fighters[1].x=210;x.fighters[0].dx=-1;stepArena(x,.016,{w:{attack:true}});settle(x);assert.equal(x.fighters[1].hp,STATS.scissors.hp);});
test('guard protects on the same frame for both player slots',()=>{for(const side of ['w','b']){const w=world('rock','rock');w.countdown=0;w.fighters[0].x=300;w.fighters[1].x=350;const opponent=side==='w'?'b':'w';stepArena(w,.016,{[side]:{attack:true},[opponent]:{guard:true}});settle(w,{[opponent]:{guard:true}});const target=w.fighters.find(f=>f.s===opponent);assert.ok(target.hp>STATS.rock.hp-STATS.rock.hit*.5);assert.ok(target.hp<STATS.rock.hp);assert.ok(target.stamina<100);}});
test('projectiles are directional and hit opponents',()=>{const w=world('paper','rock');w.countdown=0;stepArena(w,.016,{w:{attack:true}});for(let i=0;i<80;i++)stepArena(w,.016,{});assert.ok(w.fighters[1].hp<125);});
test('dash has cooldown and cannot leave the square',()=>{const w=world('scissors','rock');w.countdown=0;w.fighters[0].x=590;stepArena(w,.016,{w:{special:true}});assert.ok(w.fighters[0].x<=615);assert.ok(w.fighters[0].specialCd>5);const x=w.fighters[0].x;stepArena(w,.016,{w:{special:true}});assert.equal(w.fighters[0].x,x);});
test('unlimited duels have no hard stop, including after several minutes',()=>{const w=world();w.countdown=0;for(let i=0;i<5000;i++)stepArena(w,.04,{});assert.equal(w.done,false);assert.equal(w.time,null);});
test('at one minute the attacker wins, even with less remaining health',()=>{for(const attacker of ['w','b']){const w=world('rock','rock',{duration:60,attacker});w.countdown=0;w.fighters.find(f=>f.s===attacker).hp=30;for(let i=0;i<1499;i++)stepArena(w,.04,{});assert.equal(w.done,false);for(let i=0;i<3;i++)stepArena(w,.04,{});assert.equal(w.done,true);assert.equal(w.result.winner,attacker);assert.ok(w.result.damage[attacker]>0);}});
test('a knockout at the timer takes precedence over an attacker time win',()=>{const w=world('rock','rock',{duration:60,attacker:'w'});w.countdown=0;w.time=.01;w.fighters[0].hp=0;stepArena(w,.016,{});assert.equal(w.result.winner,'b');});
test('knockout resolves immediately and cannot resolve twice',()=>{const w=world();w.countdown=0;w.fighters[1].hp=0;stepArena(w,.016,{});assert.equal(w.result.winner,'w');const result=w.result;stepArena(w,.016,{});assert.equal(w.result,result);});
test('arena cover stops movement and blocks projectiles',()=>{const w=makeArena({w:'paper',b:'rock'},{w:[],b:[]},newGame().roster,{attacker:null});w.countdown=0;w.obstacles.push({x:210,y:165,w:40,h:50,hp:55,s:'w'});const o=w.obstacles[0];w.fighters[0].x=o.x-24;w.fighters[0].y=o.y+25;for(let i=0;i<10;i++)stepArena(w,.02,{w:{x:1}});assert.ok(w.fighters[0].x<o.x);const hp=o.hp;stepArena(w,.016,{w:{attack:true}});for(let i=0;i<15;i++)stepArena(w,.016,{});assert.ok(o.hp<hp);});
test('wounds cannot go below zero and winners have a capped wound',()=>{const g=newGame();g.roster.b.paper=10;const next=recordWounds(g,{w:'rock',b:'paper'},'w',{w:200,b:100});assert.equal(next.roster.b.paper,0);assert.equal(next.roster.w.rock,80);});
test('all nine automatic champion matchups finish without a time limit',()=>{for(const w of ['rock','scissors','paper'])for(const b of ['rock','scissors','paper']){const arena=world(w,b);for(let i=0;i<8000&&!arena.done;i++)stepArena(arena,.04,autoInput(arena));assert.ok(arena.done,`${w} vs ${b} must reach a knockout`);assert.ok(arena.result.reason.includes('knockout')||arena.result.reason==='Knockout');}});
test('automatic fights still finish with capped neighbouring support and cover',()=>{for(const w of ['rock','scissors','paper'])for(const b of ['rock','scissors','paper']){const support=Array.from({length:2},()=>['p','b','r','n'].map(t=>({t}))).flat();const arena=makeArena({w,b},{w:support,b:support},newGame().roster);for(let i=0;i<10000&&!arena.done;i++)stepArena(arena,.04,autoInput(arena));assert.ok(arena.done,`${w} vs ${b} with support must finish`);}});
test('neighbouring piece support remains a permanent core combat mechanic',()=>{
 const g=position('4k3/8/8/3p4/2NRB3/8/8/4K3','w','duel'),m=new Match(g);m.play(moves(g,idx('d4')).find(x=>x.to===idx('d5')));assert.equal(m.support.centre,idx('d5'));assert.ok(m.support.pieces.length>0);m.choose('w','rock');m.choose('b','paper');assert.equal(m.world.obstacles.length,0);const f=m.world.fighters.find(f=>f.s==='w');assert.ok(f.buff.power>0);assert.ok(f.buff.cooldown<1);assert.ok(f.buff.speed>0);
});
test('normal damage leaves more room for mistakes for every champion',()=>{for(const t of ['rock','scissors','paper']){const arena=world(t,'rock');arena.countdown=0;arena.fighters[1].x=210;stepArena(arena,.016,{w:{attack:true}});settle(arena,{},Math.ceil(RULES.rockSwingWindup/.016)+2);assert.equal(arena.fighters[1].hp,STATS.rock.hp-STATS[t].hit);}});
test('combat publishes distinct sound cues for swings, guards, projectiles and knockouts',()=>{
 const arena=world('rock','rock');arena.countdown=0;arena.fighters[1].x=210;stepArena(arena,.016,{w:{attack:true},b:{guard:true}});assert.ok(arena.events.includes('swing-rock'));const heard=new Set();for(let i=0;i<30;i++){stepArena(arena,.016,{b:{guard:true}});arena.events.forEach(e=>heard.add(e));}assert.ok(heard.has('guard'));assert.ok(heard.has('hit'));arena.fighters[1].hp=0;stepArena(arena,.016,{});assert.ok(arena.events.includes('knockout'));const mage=world('paper','rock');mage.countdown=0;stepArena(mage,.016,{w:{special:true}});assert.ok(mage.events.includes('special-paper'));
});
